package org.apache.wiki;

import rebound.annotations.semantic.meta.dependencies.DependencyClass;
import rebound.annotations.semantic.meta.dependencies.DependencyFile;

@DependencyFile("META-INF/jspwiki.tld")

@DependencyClass(org.apache.wiki.tags.AdminBeanIteratorInfo.class)
@DependencyClass(org.apache.wiki.tags.AdminBeanIteratorTag.class)
@DependencyClass(org.apache.wiki.tags.AttachmentsIteratorInfo.class)
@DependencyClass(org.apache.wiki.tags.AttachmentsIteratorTag.class)
@DependencyClass(org.apache.wiki.tags.AuthorTag.class)
@DependencyClass(org.apache.wiki.tags.BaseURLTag.class)
@DependencyClass(org.apache.wiki.tags.BreadcrumbsTag.class)
@DependencyClass(org.apache.wiki.tags.CalendarTag.class)
@DependencyClass(org.apache.wiki.tags.CheckLockInfo.class)
@DependencyClass(org.apache.wiki.tags.CheckLockTag.class)
@DependencyClass(org.apache.wiki.tags.CheckRequestContextTag.class)
@DependencyClass(org.apache.wiki.tags.CheckVersionTag.class)
@DependencyClass(org.apache.wiki.tags.CommentLinkTag.class)
@DependencyClass(org.apache.wiki.tags.ContentEncodingTag.class)
@DependencyClass(org.apache.wiki.tags.ContentTag.class)
@DependencyClass(org.apache.wiki.tags.CookieTag.class)
@DependencyClass(org.apache.wiki.tags.DiffLinkTag.class)
@DependencyClass(org.apache.wiki.tags.EditLinkTag.class)
@DependencyClass(org.apache.wiki.tags.EditorIteratorInfo.class)
@DependencyClass(org.apache.wiki.tags.EditorIteratorTag.class)
@DependencyClass(org.apache.wiki.tags.EditorTag.class)
@DependencyClass(org.apache.wiki.tags.FeedDiscoveryTag.class)
@DependencyClass(org.apache.wiki.tags.HasAttachmentsTag.class)
@DependencyClass(org.apache.wiki.tags.HistoryIteratorInfo.class)
@DependencyClass(org.apache.wiki.tags.HistoryIteratorTag.class)
@DependencyClass(org.apache.wiki.tags.IfNoSearchResultsTag.class)
@DependencyClass(org.apache.wiki.tags.IncludeResourcesTag.class)
@DependencyClass(org.apache.wiki.tags.IncludeTag.class)
@DependencyClass(org.apache.wiki.tags.InsertDiffTag.class)
@DependencyClass(org.apache.wiki.tags.InsertPageTag.class)
@DependencyClass(org.apache.wiki.tags.LinkTag.class)
@DependencyClass(org.apache.wiki.tags.LinkToParentTag.class)
@DependencyClass(org.apache.wiki.tags.LinkToTag.class)
@DependencyClass(org.apache.wiki.tags.MessagesTag.class)
@DependencyClass(org.apache.wiki.tags.NextVersionTag.class)
@DependencyClass(org.apache.wiki.tags.NoSuchPageTag.class)
@DependencyClass(org.apache.wiki.tags.PageDateTag.class)
@DependencyClass(org.apache.wiki.tags.PageExistsTag.class)
@DependencyClass(org.apache.wiki.tags.PageInfoLinkTag.class)
@DependencyClass(org.apache.wiki.tags.PageNameTag.class)
@DependencyClass(org.apache.wiki.tags.PageSizeTag.class)
@DependencyClass(org.apache.wiki.tags.PageTypeTag.class)
@DependencyClass(org.apache.wiki.tags.PageVersionTag.class)
@DependencyClass(org.apache.wiki.tags.ParamTag.class)
@DependencyClass(org.apache.wiki.tags.ParentPageNameTag.class)
@DependencyClass(org.apache.wiki.tags.PermissionTag.class)
@DependencyClass(org.apache.wiki.tags.PluginTag.class)
@DependencyClass(org.apache.wiki.tags.PreviousVersionTag.class)
@DependencyClass(org.apache.wiki.tags.RSSImageLinkTag.class)
@DependencyClass(org.apache.wiki.tags.RequestResourceTag.class)
@DependencyClass(org.apache.wiki.tags.SearchResultIteratorInfo.class)
@DependencyClass(org.apache.wiki.tags.SearchResultIteratorTag.class)
@DependencyClass(org.apache.wiki.tags.SearchResultsSizeTag.class)
@DependencyClass(org.apache.wiki.tags.SearchResultsTag.class)
@DependencyClass(org.apache.wiki.tags.SetPaginationTag.class)
@DependencyClass(org.apache.wiki.tags.SpamFilterInputsTag.class)
@DependencyClass(org.apache.wiki.tags.TabTag.class)
@DependencyClass(org.apache.wiki.tags.TabbedSectionTag.class)
@DependencyClass(org.apache.wiki.tags.TemplateDirTag.class)
@DependencyClass(org.apache.wiki.tags.TranslateTag.class)
@DependencyClass(org.apache.wiki.tags.UploadLinkTag.class)
@DependencyClass(org.apache.wiki.tags.UserCheckTag.class)
@DependencyClass(org.apache.wiki.tags.UserNameTag.class)
@DependencyClass(org.apache.wiki.tags.UserProfileTag.class)
@DependencyClass(org.apache.wiki.tags.VariableTag.class)
public class DependenciesOfJSPTagLibrary
{
}
